name: flutter_tdd
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^0.1.3
  # Service Locator
  get_it: ^5.0.1
  # Bloc for state management
  flutter_bloc: ^6.0.5
  # Value Equality
  equatable: ^1.2.5
  # Functional Programming
  dartz: ^0.9.1
  # Remote API
  connectivity: ^0.4.9+3
  http: ^0.12.2
  # Local Storage
  shared_preferences: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mock Tests
  mockito: ^4.1.0



flutter:

  uses-material-design: true

  assets :
    - assets/
